import { FaRegSmile } from "react-icons/fa";
import OrdersTable from "../../../hooks/OrdersTable/OrdersTable";

const WholesalerOrders = () => {
 const wholesalerOrdersData = [
   {
     sn: "01",
     trackingNo: "#W2345",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "500",
     totalEarning: "50,000 TK",
     orderDate: "01/02/2024",
     status: "Done",
   },
   {
     sn: "02",
     trackingNo: "#W2326",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "300",
     totalEarning: "30,000 TK",
     orderDate: "01/02/2025",
     status: "Done",
   },
   {
     sn: "03",
     trackingNo: "#W2365",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "200",
     totalEarning: "20,000 TK",
     orderDate: "01/02/2025",
     status: "Pending",
   },
   {
     sn: "04",
     trackingNo: "#W2346",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "150",
     totalEarning: "15,000 TK",
     orderDate: "02/02/2025",
     status: "Pending",
   },
   {
     sn: "05",
     trackingNo: "#W2347",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "250",
     totalEarning: "25,000 TK",
     orderDate: "02/02/2025",
     status: "Pending",
   },
   {
     sn: "06",
     trackingNo: "#W2348",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "350",
     totalEarning: "35,000 TK",
     orderDate: "02/02/2025",
     status: "Done",
   },
   {
     sn: "07",
     trackingNo: "#W2349",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "100",
     totalEarning: "10,000 TK",
     orderDate: "03/02/2025",
     status: "Pending",
   },
   {
     sn: "08",
     trackingNo: "#W2350",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "180",
     totalEarning: "18,000 TK",
     orderDate: "03/02/2025",
     status: "Done",
   },
   {
     sn: "09",
     trackingNo: "#W2351",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "250",
     totalEarning: "25,000 TK",
     orderDate: "03/02/2025",
     status: "Done",
   },
   {
     sn: "10",
     trackingNo: "#W2352",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "120",
     totalEarning: "12,000 TK",
     orderDate: "04/02/2025",
     status: "Done",
   },
   {
     sn: "11",
     trackingNo: "#W2353",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "500",
     totalEarning: "50,000 TK",
     orderDate: "04/02/2025",
     status: "Pending",
   },
   {
     sn: "12",
     trackingNo: "#W2354",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "450",
     totalEarning: "45,000 TK",
     orderDate: "04/02/2025",
     status: "Pending",
   },
   {
     sn: "13",
     trackingNo: "#W2355",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "200",
     totalEarning: "20,000 TK",
     orderDate: "05/02/2025",
     status: "Done",
   },
   {
     sn: "14",
     trackingNo: "#W2356",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "100",
     totalEarning: "10,000 TK",
     orderDate: "05/02/2025",
     status: "Done",
   },
   {
     sn: "15",
     trackingNo: "#W2357",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "200",
     totalEarning: "20,000 TK",
     orderDate: "05/02/2025",
     status: "Pending",
   },
   {
     sn: "16",
     trackingNo: "#W2358",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "300",
     totalEarning: "30,000 TK",
     orderDate: "06/02/2025",
     status: "Pending",
   },
   {
     sn: "17",
     trackingNo: "#W2359",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "600",
     totalEarning: "60,000 TK",
     orderDate: "06/02/2025",
     status: "Done",
   },
   {
     sn: "18",
     trackingNo: "#W2360",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "150",
     totalEarning: "15,000 TK",
     orderDate: "06/02/2025",
     status: "Done",
   },
   {
     sn: "19",
     trackingNo: "#W2361",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "500",
     totalEarning: "50,000 TK",
     orderDate: "07/02/2025",
     status: "Pending",
   },
   {
     sn: "20",
     trackingNo: "#W2362",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "400",
     totalEarning: "40,000 TK",
     orderDate: "07/02/2025",
     status: "Done",
   },
   {
     sn: "21",
     trackingNo: "#W2363",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "100",
     totalEarning: "10,000 TK",
     orderDate: "07/02/2025",
     status: "Done",
   },
   {
     sn: "22",
     trackingNo: "#W2364",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "600",
     totalEarning: "60,000 TK",
     orderDate: "08/02/2025",
     status: "Pending",
   },
   {
     sn: "23",
     trackingNo: "#W2365",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "200",
     totalEarning: "20,000 TK",
     orderDate: "08/02/2025",
     status: "Done",
   },
   {
     sn: "24",
     trackingNo: "#W2366",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "300",
     totalEarning: "30,000 TK",
     orderDate: "08/02/2025",
     status: "Pending",
   },
   {
     sn: "25",
     trackingNo: "#W2367",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "150",
     totalEarning: "15,000 TK",
     orderDate: "09/02/2025",
     status: "Pending",
   },
   {
     sn: "26",
     trackingNo: "#W2368",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "700",
     totalEarning: "70,000 TK",
     orderDate: "09/02/2025",
     status: "Done",
   },
   {
     sn: "27",
     trackingNo: "#W2369",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "250",
     totalEarning: "25,000 TK",
     orderDate: "09/02/2025",
     status: "Done",
   },
   {
     sn: "28",
     trackingNo: "#W2370",
     productName: "Wholesaler Rice/পেঁদা ধান",
     quantity: "400",
     totalEarning: "40,000 TK",
     orderDate: "10/02/2025",
     status: "Done",
   },
   {
     sn: "29",
     trackingNo: "#W2371",
     productName: "Wholesaler Jute/পেঁদা পাঁট",
     quantity: "500",
     totalEarning: "50,000 TK",
     orderDate: "10/02/2025",
     status: "Pending",
   },
   {
     sn: "30",
     trackingNo: "#W2372",
     productName: "Wholesaler Corn/পেঁদা ভুট্টা",
     quantity: "350",
     totalEarning: "35,000 TK",
     orderDate: "10/02/2025",
     status: "Done",
   },
 ];


  return (
    <div>
      <div className="flex items-center justify-between px-4">
        <div className="text-lg font-semibold text-gray-700 mt-4 flex items-center">
          <FaRegSmile className="mr-2 text-green-500" /> Wholesaler Orders
        </div>
      </div>
      <OrdersTable data={wholesalerOrdersData} />
    </div>
  );
};

export default WholesalerOrders;


