import { FaRegSmile } from "react-icons/fa";
import OrdersTable from "../../../hooks/OrdersTable/OrdersTable";

const SuperSellerOrders = () => {
  const superSellerOrdersData = [
    {
      sn: "01",
      trackingNo: "#S2345",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "200",
      totalEarning: "20,000 TK",
      orderDate: "01/02/2024",
      status: "Done",
    },
    {
      sn: "02",
      trackingNo: "#S2326",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "150",
      totalEarning: "15,000 TK",
      orderDate: "01/02/2025",
      status: "Done",
    },
    {
      sn: "03",
      trackingNo: "#S2365",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "300",
      totalEarning: "30,000 TK",
      orderDate: "01/02/2025",
      status: "Pending",
    },
    {
      sn: "04",
      trackingNo: "#S2346",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "400",
      totalEarning: "40,000 TK",
      orderDate: "02/02/2025",
      status: "Pending",
    },
    {
      sn: "05",
      trackingNo: "#S2347",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "250",
      totalEarning: "25,000 TK",
      orderDate: "02/02/2025",
      status: "Pending",
    },
    {
      sn: "06",
      trackingNo: "#S2348",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "500",
      totalEarning: "50,000 TK",
      orderDate: "02/02/2025",
      status: "Done",
    },
    {
      sn: "07",
      trackingNo: "#S2349",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "100",
      totalEarning: "10,000 TK",
      orderDate: "03/02/2025",
      status: "Pending",
    },
    {
      sn: "08",
      trackingNo: "#S2350",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "300",
      totalEarning: "30,000 TK",
      orderDate: "03/02/2025",
      status: "Done",
    },
    {
      sn: "09",
      trackingNo: "#S2351",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "150",
      totalEarning: "15,000 TK",
      orderDate: "03/02/2025",
      status: "Done",
    },
    {
      sn: "10",
      trackingNo: "#S2352",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "250",
      totalEarning: "25,000 TK",
      orderDate: "04/02/2025",
      status: "Done",
    },
    {
      sn: "11",
      trackingNo: "#S2353",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "400",
      totalEarning: "40,000 TK",
      orderDate: "04/02/2025",
      status: "Pending",
    },
    {
      sn: "12",
      trackingNo: "#S2354",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "350",
      totalEarning: "35,000 TK",
      orderDate: "04/02/2025",
      status: "Pending",
    },
    {
      sn: "13",
      trackingNo: "#S2355",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "500",
      totalEarning: "50,000 TK",
      orderDate: "05/02/2025",
      status: "Done",
    },
    {
      sn: "14",
      trackingNo: "#S2356",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "200",
      totalEarning: "20,000 TK",
      orderDate: "05/02/2025",
      status: "Done",
    },
    {
      sn: "15",
      trackingNo: "#S2357",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "100",
      totalEarning: "10,000 TK",
      orderDate: "05/02/2025",
      status: "Pending",
    },
    {
      sn: "16",
      trackingNo: "#S2358",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "300",
      totalEarning: "30,000 TK",
      orderDate: "06/02/2025",
      status: "Pending",
    },
    {
      sn: "17",
      trackingNo: "#S2359",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "600",
      totalEarning: "60,000 TK",
      orderDate: "06/02/2025",
      status: "Done",
    },
    {
      sn: "18",
      trackingNo: "#S2360",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "450",
      totalEarning: "45,000 TK",
      orderDate: "06/02/2025",
      status: "Done",
    },
    {
      sn: "19",
      trackingNo: "#S2361",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "600",
      totalEarning: "60,000 TK",
      orderDate: "07/02/2025",
      status: "Pending",
    },
    {
      sn: "20",
      trackingNo: "#S2362",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "100",
      totalEarning: "10,000 TK",
      orderDate: "07/02/2025",
      status: "Done",
    },
    {
      sn: "21",
      trackingNo: "#S2363",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "200",
      totalEarning: "20,000 TK",
      orderDate: "07/02/2025",
      status: "Done",
    },
    {
      sn: "22",
      trackingNo: "#S2364",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "500",
      totalEarning: "50,000 TK",
      orderDate: "08/02/2025",
      status: "Pending",
    },
    {
      sn: "23",
      trackingNo: "#S2365",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "250",
      totalEarning: "25,000 TK",
      orderDate: "08/02/2025",
      status: "Done",
    },
    {
      sn: "24",
      trackingNo: "#S2366",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "300",
      totalEarning: "30,000 TK",
      orderDate: "08/02/2025",
      status: "Pending",
    },
    {
      sn: "25",
      trackingNo: "#S2367",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "350",
      totalEarning: "35,000 TK",
      orderDate: "09/02/2025",
      status: "Pending",
    },
    {
      sn: "26",
      trackingNo: "#S2368",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "500",
      totalEarning: "50,000 TK",
      orderDate: "09/02/2025",
      status: "Done",
    },
    {
      sn: "27",
      trackingNo: "#S2369",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "400",
      totalEarning: "40,000 TK",
      orderDate: "09/02/2025",
      status: "Done",
    },
    {
      sn: "28",
      trackingNo: "#S2370",
      productName: "SuperSeller Rice/বিশ্বস্ত ধান",
      quantity: "200",
      totalEarning: "20,000 TK",
      orderDate: "10/02/2025",
      status: "Done",
    },
    {
      sn: "29",
      trackingNo: "#S2371",
      productName: "SuperSeller Jute/বিশ্বস্ত পাঁট",
      quantity: "150",
      totalEarning: "15,000 TK",
      orderDate: "10/02/2025",
      status: "Pending",
    },
    {
      sn: "30",
      trackingNo: "#S2372",
      productName: "SuperSeller Corn/বিশ্বস্ত ভুট্টা",
      quantity: "250",
      totalEarning: "25,000 TK",
      orderDate: "10/02/2025",
      status: "Done",
    },
  ];


  return (
    <div>
      <div className="flex items-center justify-between px-4">
        <div className="text-lg mt-4 font-semibold text-gray-700 flex items-center">
          <FaRegSmile className="mr-2 text-green-500" /> Super Seller Orders
        </div>
      </div>
      <OrdersTable data={superSellerOrdersData} />
    </div>
  );
};

export default SuperSellerOrders;
